//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.SingInServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Contracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.SingInServiceProxy.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.SingInServiceProxy.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalDetail {
            get {
                return this.TechnicalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalDetailField, value) != true)) {
                    this.TechnicalDetailField = value;
                    this.RaisePropertyChanged("TechnicalDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCredentials = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameEmpty = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileNotFound = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsLoadError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldLengthExceeded = 3008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatOpenError = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavigationError = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SoundVolumeInvalid = 3011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationInterrupted = 3012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSendingError = 3013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSentSuccessfully = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatUnavailable = 3015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SoundSettingsUpdated = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SoundSettingsError = 4002,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingInServiceProxy.ISingInService")]
    public interface ISingInService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/ValidateUserData", ReplyAction="http://tempuri.org/ISingInService/ValidateUserDataResponse")]
        DamasChinas_Client.UI.SingInServiceProxy.OperationResult ValidateUserData(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/ValidateUserData", ReplyAction="http://tempuri.org/ISingInService/ValidateUserDataResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> ValidateUserDataAsync(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/RequestVerificationCode", ReplyAction="http://tempuri.org/ISingInService/RequestVerificationCodeResponse")]
        DamasChinas_Client.UI.SingInServiceProxy.OperationResult RequestVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/RequestVerificationCode", ReplyAction="http://tempuri.org/ISingInService/RequestVerificationCodeResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> RequestVerificationCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/CreateUser", ReplyAction="http://tempuri.org/ISingInService/CreateUserResponse")]
        DamasChinas_Client.UI.SingInServiceProxy.OperationResult CreateUser(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingInService/CreateUser", ReplyAction="http://tempuri.org/ISingInService/CreateUserResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> CreateUserAsync(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto, string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingInServiceChannel : DamasChinas_Client.UI.SingInServiceProxy.ISingInService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingInServiceClient : System.ServiceModel.ClientBase<DamasChinas_Client.UI.SingInServiceProxy.ISingInService>, DamasChinas_Client.UI.SingInServiceProxy.ISingInService {
        
        public SingInServiceClient() {
        }
        
        public SingInServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingInServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingInServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingInServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.SingInServiceProxy.OperationResult ValidateUserData(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto) {
            return base.Channel.ValidateUserData(userDto);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> ValidateUserDataAsync(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto) {
            return base.Channel.ValidateUserDataAsync(userDto);
        }
        
        public DamasChinas_Client.UI.SingInServiceProxy.OperationResult RequestVerificationCode(string email) {
            return base.Channel.RequestVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> RequestVerificationCodeAsync(string email) {
            return base.Channel.RequestVerificationCodeAsync(email);
        }
        
        public DamasChinas_Client.UI.SingInServiceProxy.OperationResult CreateUser(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto, string code) {
            return base.Channel.CreateUser(userDto, code);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.SingInServiceProxy.OperationResult> CreateUserAsync(DamasChinas_Client.UI.SingInServiceProxy.UserDto userDto, string code) {
            return base.Channel.CreateUserAsync(userDto, code);
        }
    }
}
