//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.FriendServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConnectionStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ConnectionState {
            get {
                return this.ConnectionStateField;
            }
            set {
                if ((this.ConnectionStateField.Equals(value) != true)) {
                    this.ConnectionStateField = value;
                    this.RaisePropertyChanged("ConnectionState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendServiceProxy.IFriendService")]
    public interface IFriendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/GetFriendsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriends(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendService/GetFriendRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/GetFriendRequestsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriendRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendService/GetFriendRequestsResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendRequestsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/SendFriendRequestStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        bool SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriend", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/DeleteFriendStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        bool DeleteFriend(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriend", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendResponse")]
        System.Threading.Tasks.Task<bool> DeleteFriendAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateBlockStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateBlockStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/UpdateBlockStatusStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        bool UpdateBlockStatus(string blockerUsername, string blockedUsername, bool block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateBlockStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateBlockStatusResponse")]
        System.Threading.Tasks.Task<bool> UpdateBlockStatusAsync(string blockerUsername, string blockedUsername, bool block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateFriendRequestStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateFriendRequestStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IFriendService/UpdateFriendRequestStatusStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        bool UpdateFriendRequestStatus(string receiverUsername, string senderUsername, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateFriendRequestStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateFriendRequestStatusResponse")]
        System.Threading.Tasks.Task<bool> UpdateFriendRequestStatusAsync(string receiverUsername, string senderUsername, bool accept);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendServiceChannel : DamasChinas_Client.UI.FriendServiceProxy.IFriendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendServiceClient : System.ServiceModel.ClientBase<DamasChinas_Client.UI.FriendServiceProxy.IFriendService>, DamasChinas_Client.UI.FriendServiceProxy.IFriendService {
        
        public FriendServiceClient() {
        }
        
        public FriendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriends(string username) {
            return base.Channel.GetFriends(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendsAsync(string username) {
            return base.Channel.GetFriendsAsync(username);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriendRequests(string username) {
            return base.Channel.GetFriendRequests(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendRequestsAsync(string username) {
            return base.Channel.GetFriendRequestsAsync(username);
        }
        
        public bool SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public bool DeleteFriend(string username, string friendUsername) {
            return base.Channel.DeleteFriend(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFriendAsync(string username, string friendUsername) {
            return base.Channel.DeleteFriendAsync(username, friendUsername);
        }
        
        public bool UpdateBlockStatus(string blockerUsername, string blockedUsername, bool block) {
            return base.Channel.UpdateBlockStatus(blockerUsername, blockedUsername, block);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBlockStatusAsync(string blockerUsername, string blockedUsername, bool block) {
            return base.Channel.UpdateBlockStatusAsync(blockerUsername, blockedUsername, block);
        }
        
        public bool UpdateFriendRequestStatus(string receiverUsername, string senderUsername, bool accept) {
            return base.Channel.UpdateFriendRequestStatus(receiverUsername, senderUsername, accept);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFriendRequestStatusAsync(string receiverUsername, string senderUsername, bool accept) {
            return base.Channel.UpdateFriendRequestStatusAsync(receiverUsername, senderUsername, accept);
        }
    }
}
